name: Build Status

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Run unit tests
      run: |
        make clean fmt test

    - name: Commits
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply fmt changes